name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: ${{ secrets.FLASK_ENV }}
          FLASK_APP: ${{ secrets.FLASK_APP }}
          DB_URI: ${{ secrets.DB_URI }}
          DB_URI_TEST: ${{ secrets.DB_URI_TEST }}
          DB_URI_DEV: ${{ secrets.DB_URI_DEV }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd src
          python -m unittest discover -s tests/ -v
      - name: Validate Styling
        run: |
          cd src
          flake8 .